/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Lucas
 */
public class TelaMenu extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenu
     */
    public TelaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnComoSeSenteHoje = new javax.swing.JButton();
        btnHistoricoFamiliar = new javax.swing.JButton();
        btnMedicamentos = new javax.swing.JButton();
        btnAtendimentoTelepresencial = new javax.swing.JButton();
        btnSugestões = new javax.swing.JButton();
        btnLigarParaCentral = new javax.swing.JButton();
        btnQuestionario = new javax.swing.JButton();
        btnMeuPontuario = new javax.swing.JButton();
        btnEditarDados = new javax.swing.JButton();
        btnRedeDeEmergencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/TelaMenu(R).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 540, 810);

        btnComoSeSenteHoje.setText("jButton1");
        btnComoSeSenteHoje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComoSeSenteHojeActionPerformed(evt);
            }
        });
        getContentPane().add(btnComoSeSenteHoje);
        btnComoSeSenteHoje.setBounds(70, 155, 80, 60);

        btnHistoricoFamiliar.setText("Historico fam.");
        btnHistoricoFamiliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoricoFamiliarActionPerformed(evt);
            }
        });
        getContentPane().add(btnHistoricoFamiliar);
        btnHistoricoFamiliar.setBounds(240, 155, 80, 60);

        btnMedicamentos.setText("jButton3");
        btnMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicamentosActionPerformed(evt);
            }
        });
        getContentPane().add(btnMedicamentos);
        btnMedicamentos.setBounds(390, 160, 80, 60);

        btnAtendimentoTelepresencial.setText("jButton4");
        btnAtendimentoTelepresencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtendimentoTelepresencialActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtendimentoTelepresencial);
        btnAtendimentoTelepresencial.setBounds(70, 300, 80, 60);

        btnSugestões.setText("jButton5");
        btnSugestões.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSugestõesActionPerformed(evt);
            }
        });
        getContentPane().add(btnSugestões);
        btnSugestões.setBounds(240, 300, 80, 60);

        btnLigarParaCentral.setText("jButton6");
        btnLigarParaCentral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLigarParaCentralActionPerformed(evt);
            }
        });
        getContentPane().add(btnLigarParaCentral);
        btnLigarParaCentral.setBounds(390, 300, 80, 60);

        btnQuestionario.setText("jButton7");
        btnQuestionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuestionarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuestionario);
        btnQuestionario.setBounds(70, 480, 80, 60);

        btnMeuPontuario.setText("jButton8");
        btnMeuPontuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMeuPontuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnMeuPontuario);
        btnMeuPontuario.setBounds(240, 480, 80, 60);

        btnEditarDados.setText("jButton9");
        btnEditarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarDadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditarDados);
        btnEditarDados.setBounds(400, 480, 80, 60);

        btnRedeDeEmergencia.setText("Rede de Emergência");
        btnRedeDeEmergencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedeDeEmergenciaActionPerformed(evt);
            }
        });
        getContentPane().add(btnRedeDeEmergencia);
        btnRedeDeEmergencia.setBounds(100, 730, 360, 60);

        setSize(new java.awt.Dimension(549, 830));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnComoSeSenteHojeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComoSeSenteHojeActionPerformed
        // TODO add your handling code here:
        new TelaComoSeSente().setVisible(true);
    }//GEN-LAST:event_btnComoSeSenteHojeActionPerformed

    private void btnEditarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDadosActionPerformed
        // TODO add your handling code here:
        new TelaEditarDados().setVisible(true);
    }//GEN-LAST:event_btnEditarDadosActionPerformed

    private void btnMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicamentosActionPerformed
        // TODO add your handling code here:
        new TelaMedicamentos().setVisible(true);
    }//GEN-LAST:event_btnMedicamentosActionPerformed

    private void btnLigarParaCentralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLigarParaCentralActionPerformed
        // TODO add your handling code here:
        new TelaLigar().setVisible(true);
    }//GEN-LAST:event_btnLigarParaCentralActionPerformed

    private void btnHistoricoFamiliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoricoFamiliarActionPerformed
        // TODO add your handling code here:
        new TelaHistorico().setVisible(true);
    }//GEN-LAST:event_btnHistoricoFamiliarActionPerformed

    private void btnAtendimentoTelepresencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtendimentoTelepresencialActionPerformed
        // TODO add your handling code here:
        new TelaAtendimento().setVisible(true);
    }//GEN-LAST:event_btnAtendimentoTelepresencialActionPerformed

    private void btnSugestõesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSugestõesActionPerformed
        // TODO add your handling code here:
        new TelaSugestões().setVisible(true);
    }//GEN-LAST:event_btnSugestõesActionPerformed

    private void btnQuestionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuestionarioActionPerformed
        // TODO add your handling code here:
        new TelaQuestionario().setVisible(true);
    }//GEN-LAST:event_btnQuestionarioActionPerformed

    private void btnMeuPontuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMeuPontuarioActionPerformed
        // TODO add your handling code here:
        new TelaPontuario().setVisible(true);
    }//GEN-LAST:event_btnMeuPontuarioActionPerformed

    private void btnRedeDeEmergenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedeDeEmergenciaActionPerformed
        // TODO add your handling code here:
        new TelaEmergencia().setVisible(true);
    }//GEN-LAST:event_btnRedeDeEmergenciaActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtendimentoTelepresencial;
    private javax.swing.JButton btnComoSeSenteHoje;
    private javax.swing.JButton btnEditarDados;
    private javax.swing.JButton btnHistoricoFamiliar;
    private javax.swing.JButton btnLigarParaCentral;
    private javax.swing.JButton btnMedicamentos;
    private javax.swing.JButton btnMeuPontuario;
    private javax.swing.JButton btnQuestionario;
    private javax.swing.JButton btnRedeDeEmergencia;
    private javax.swing.JButton btnSugestões;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
