/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import javax.swing.JOptionPane;

/**
 *
 * @author Lucas
 */
public class TelaAtendimento extends javax.swing.JFrame {

    /**
     * Creates new form TelaAtendimento
     */
    public TelaAtendimento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnParticipar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        btnParticipar.setBackground(new java.awt.Color(0, 0, 0));
        btnParticipar.setForeground(new java.awt.Color(255, 255, 255));
        btnParticipar.setText("Participar");
        btnParticipar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParticiparActionPerformed(evt);
            }
        });
        getContentPane().add(btnParticipar);
        btnParticipar.setBounds(190, 690, 160, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/TelaAtendimento(R).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 510, 790);

        setSize(new java.awt.Dimension(520, 801));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnParticiparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParticiparActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Aguarde alguns momentos, pode demorar um pouco (WIP)");
    }//GEN-LAST:event_btnParticiparActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnParticipar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
