/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import javax.swing.JOptionPane;

/**
 *
 * @author Lucas
 */
public class TelaComoSeSente extends javax.swing.JFrame {

    /**
     * Creates new form TelaComoSeSente
     */
    public TelaComoSeSente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEnviar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAlegre = new javax.swing.JButton();
        btnTriste = new javax.swing.JButton();
        btnPreocupado = new javax.swing.JButton();
        btnSumico = new javax.swing.JButton();
        btnSuicidio = new javax.swing.JButton();
        btnSolidao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        btnEnviar.setBackground(new java.awt.Color(0, 0, 0));
        btnEnviar.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar);
        btnEnviar.setBounds(166, 728, 200, 45);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/TelaComoSeSente(R).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 510, 800);

        btnAlegre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlegreActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlegre);
        btnAlegre.setBounds(58, 222, 95, 90);

        btnTriste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTristeActionPerformed(evt);
            }
        });
        getContentPane().add(btnTriste);
        btnTriste.setBounds(218, 220, 95, 92);

        btnPreocupado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreocupadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPreocupado);
        btnPreocupado.setBounds(367, 221, 97, 91);

        btnSumico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumicoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSumico);
        btnSumico.setBounds(55, 459, 95, 90);

        btnSuicidio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuicidioActionPerformed(evt);
            }
        });
        getContentPane().add(btnSuicidio);
        btnSuicidio.setBounds(217, 457, 95, 92);

        btnSolidao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolidaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSolidao);
        btnSolidao.setBounds(380, 457, 97, 92);

        setSize(new java.awt.Dimension(524, 825));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlegreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlegreActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Opção 'Alegre' selecionada");
    }//GEN-LAST:event_btnAlegreActionPerformed

    private void btnTristeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTristeActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Opção 'Triste' selecionada");
    }//GEN-LAST:event_btnTristeActionPerformed

    private void btnPreocupadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreocupadoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Opção 'Preocupado(a)' selecionada");
    }//GEN-LAST:event_btnPreocupadoActionPerformed

    private void btnSumicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumicoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Opção 'Sumiço' selecionada");
    }//GEN-LAST:event_btnSumicoActionPerformed

    private void btnSuicidioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuicidioActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Opção 'Suicídio' selecionada");
    }//GEN-LAST:event_btnSuicidioActionPerformed

    private void btnSolidaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolidaoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Opção 'Solidão' selecionada");
    }//GEN-LAST:event_btnSolidaoActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Obrigado por informar");
        dispose();
    }//GEN-LAST:event_btnEnviarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlegre;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnPreocupado;
    private javax.swing.JButton btnSolidao;
    private javax.swing.JButton btnSuicidio;
    private javax.swing.JButton btnSumico;
    private javax.swing.JButton btnTriste;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
